# Generated by Django 4.0.5 on 2022-06-10 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_name', models.CharField(max_length=50)),
                ('profile', models.CharField(max_length=50)),
                ('salary', models.FloatField()),
                ('email', models.EmailField(max_length=254)),
                ('mblno', models.IntegerField()),
                ('picture', models.ImageField(upload_to='pic')),
                ('resume', models.FileField(upload_to='mediafile')),
            ],
        ),
    ]
